import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import './globals.css';




import AuthProvider from "@/context/AuthProvider";

import { Toaster } from "@/components/ui/sonner"
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

            <AuthProvider>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    {children}
                    <Toaster
                        toastOptions={{
                            style: {
                                background: '#3d3b3b',  
                                color: '#fff',          
                            },
                        }}
                    />

                </body>

            </AuthProvider>
        </html>
    );
}
